import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'ro' | 'ru';

type LanguageProviderProps = {
  children: React.ReactNode;
  defaultLanguage?: Language;
  storageKey?: string;
};

type LanguageProviderState = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const initialState: LanguageProviderState = {
  language: 'en',
  setLanguage: () => null,
  t: (key: string) => key,
};

const LanguageProviderContext = createContext<LanguageProviderState>(initialState);

// Translation object
const translations: Record<Language, Record<string, string>> = {
  en: {

    //bug fix
    'community.message': 'Message',
    'community.friends': 'Friends',
    'community.searchUsers': 'Search users',
    'community.requests': 'Requests',
    'community.blocked': 'Blocked',
    'mobile.signOut': 'Sign Out',

    // Navigation
    'nav.welcome': 'Welcome',
    'nav.profile': 'Profile',
    'nav.menu': 'Menu',
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.signOut': 'Sign Out',
    'nav.report': 'Report',
    'nav.emergency': 'Emergency',
    'nav.navigation': 'Navigation',
    'nav.qrCode': 'QR Code',
    'nav.title': 'Driver Assistance Platform',
    'nav.admin'  : 'Admin',
    
    //Friend Modal
    'friends.title':'Friends',
    'friends.description':'Description',
    // Auth page
    'auth.hello': 'Hello there!',
    'auth.subtitle': 'Sign in to access your driver dashboard',
    'auth.welcomeTo': 'Welcome to',
    'auth.platformName': 'DAP Platform',
    'auth.tagline': 'Your intelligent driving companion for safer, smarter journeys',
    'auth.smartNavigation': 'Smart Navigation',
    'auth.emergencySupport': 'Emergency Support',
    'auth.communityDriven': 'Community Driven',
    'auth.backToHome': 'Back to Home',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.signIn': 'Sign In',
    'auth.getStarted': 'Get Started',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.createPassword': 'Create a password',
    'auth.confirmPassword': 'Confirm your password',
    'auth.emailRequired': 'Email is required',
    'auth.passwordRequired': 'Password is required',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    'auth.confirmPasswordRequired': 'Please confirm your password',
    'auth.signingIn': 'Signing In...',
    'auth.creatingAccount': 'Creating Account...',
    'auth.createAccount': 'Create Account',
    'auth.welcomeBack': 'Welcome back',
    'auth.signInToContinue': 'Sign in to your account to continue',
    'auth.joinCommunity': 'Join our community to get started',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.signUp': 'Sign Up',
    'auth.signInWithEmail': 'Sign in with email',
    'auth.signUpWithEmail': 'Sign up with email',

    // Dashboard
    'dashboard.title': 'Driver Assistance',
    'dashboard.welcome': 'Welcome',
    'dashboard.subtitle': 'Choose an option below to get started',
    'menu': 'Menu',
    'home': 'Home',
    'qrCode': 'QR Code',

    // Profile Modal
    'profile.title': 'My Profile',
    'profile.profileTab': 'Profile',
    'profile.carsTab': 'Cars',
    'profile.servicesTab': 'Services',
    'profile.accountTab': 'Account',
    'profile.personalInfo': 'Personal Information',
    'profile.changePhoto': 'Change Photo',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.phoneNumber': 'Phone Number',
    'profile.saveProfile': 'Save Profile',
    'profile.noCarsRegistered': 'No cars registered',
    'profile.addCar': 'Add Car',
    'profile.noServicesRecorded': 'No services recorded',
    'profile.addService': 'Add Service',
    'profile.camera': 'Camera',
    'profile.upload': 'Upload',
    'profile.firstNamePlaceholder': 'Enter your first name',
    'profile.lastNamePlaceholder': 'Enter your last name',
    'profile.phoneNumberPlaceholder': 'Enter your phone number',
    'profile.myCars': 'My Cars',
    'profile.noCarsAdded': 'No cars added yet',
    'profile.addNewCar': 'Add New Car',
    'profile.carName': 'Car Name',
    'profile.carNamePlaceholder': 'e.g., My Toyota',
    'profile.model': 'Model',
    'profile.modelPlaceholder': 'e.g., Camry',
    'profile.plateNumber': 'Plate Number',
    'profile.plateNumberPlaceholder': 'e.g., ABC-123',
    'profile.carPhoneNumber': 'Car Phone Number',
    'profile.carPhonePlaceholder': 'Emergency contact number',
    'profile.cancel': 'Cancel',
    'profile.myServices': 'My Services',
    'profile.noServicesAdded': 'No services added yet',
    'profile.accountSettings': 'Account Settings',
    'profile.email': 'Email',
    'profile.change': 'Change',
    'profile.password': 'Password',
    'profile.passwordDesc': 'Last changed 30 days ago',
    'profile.deleteAccount': 'Delete Account',
    'profile.deleteAccountDesc': 'Permanently delete your account and all data',
    'profile.delete': 'Delete',
    'profile.qrCode': 'QR Code',
    'profile.qrCodeDesc': 'No QR code generated yet',
    'profile.generateQR': 'Generate QR Code',
    'profile.updateQR': 'Update QR Code',
    'profile.downloadQR': 'Download',
    'profile.uploading': 'Uploading...',
    'profile.avatarUpdated': 'Avatar Updated',
    'profile.avatarUpdatedDesc': 'Your profile photo has been updated successfully.',
    'profile.uploadFailed': 'Upload Failed',
    'profile.uploadFailedDesc': 'Failed to upload image. Please try again.',
    'profile.profileSaved': 'Profile Saved',
    'profile.profileSavedDesc': 'Your profile has been updated successfully.',
    'profile.carAdded': 'Car Added',
    'profile.carAddedDesc': 'Your car has been added successfully.',

    // Emergency Modal
    'emergency.title': 'Emergency Services',
    'emergency.selectService': 'Select an emergency service below. You can add additional information before making the call.',
    'emergency.services.ambulance': 'Ambulance',
    'emergency.services.police': 'Police',
    'emergency.services.fire': 'Fire Department',
    'emergency.services.ambulanceDesc': 'Medical emergencies and health-related incidents',
    'emergency.services.policeDesc': 'Criminal activities, accidents, and security issues',
    'emergency.services.fireDesc': 'Fires, gas leaks, and rescue operations',
    'emergency.importantNotice': 'Important Notice',
    'emergency.onlyGenuineEmergencies': 'These are emergency contact numbers. Please only use them for genuine emergencies. For non-urgent matters, contact the appropriate non-emergency services.',
    'emergency.additionalInfo': 'Additional Information (Optional)',
    'emergency.changeService': 'Change Service',
    'emergency.addDetails': 'Add Details',
    'emergency.additionalInfoPlaceholder': 'Provide any additional information that might help emergency responders...',
    'emergency.attachImage': 'Attach Image (Optional)',
    'emergency.uploadImage': 'Upload Image',
    'emergency.chooseImage': 'Choose Image',
    'emergency.dialerNote': 'You will be redirected to your phone\'s dialer with the emergency number pre-filled. Please ensure you have a stable connection before proceeding.',
    'emergency.back': 'Back',
    'emergency.call': 'Call',

    // Navigation Modal
    'navigation.title': 'Navigation',
    'navigation.getDirections': 'Get directions to your destination using the map below. Select a location to start navigation.',
    'navigation.clickOnMap': 'Select Location',
    'navigation.mapUnavailable': 'Map is unavailable in this demo.',
    'navigation.findPlaces': 'Find places by name or address',
    'navigation.nearbyLocations': 'Nearby Locations',
    'navigation.trafficInfo': 'Real-time traffic information',
    'navigation.currentTraffic': 'Current Traffic',
    'navigation.savedRoutes': 'Saved Routes',
    'navigation.frequentDestinations': 'Frequent Destinations',

       //Penalty Management
    'penalties.myPenalties': 'My Penalties',
    'penalties.activePenalties': 'Active Penalties',
    'penalties.totalPoints': 'Total Points',
    'penalties.unpaidFines': 'Unpaid Fines',
    'penalties.addPenalty': 'Add Penalty',

    // Service Management
    'service.title': 'Service Management',
    'service.subtitle': 'Manage your vehicle services, maintenance records, and important dates.',
    'service.addService': 'Add Service',
    'service.type': 'Service Type',
    'service.description': 'Description',
    'service.price': 'Price',
    'service.date': 'Service Date',
    'service.expiryDate': 'Expiry Date',
    'service.expires': 'Expires',

    // Cards
    'cards.reportProblem.title': 'Report Problem',
    'cards.reportProblem.description': 'Report issues with vehicles or road conditions to other drivers',
    'cards.qrCode.title': 'Generate QR Code',
    'cards.qrCode.description': 'Create a QR code with your profile and car information',
    'cards.emergency.title': 'Emergency',
    'cards.emergency.description': 'Quick access to emergency services with optional comments and images',
    'cards.navigation.title': 'Navigation',
    'cards.navigation.description': 'Interactive map navigation to help you find your way',
    'cards.service.title': 'Service',
    'cards.service.description': 'Manage your vehicle services, insurance, and maintenance records',
    'cards.community.title': 'Community',
    'cards.community.description': 'Connect with other drivers, add friends, and start conversations',
    'cards.penalties.title': 'Penalty Management',
    'cards.penalties.description': 'View active and inactive road penalties, payment status, and manage your driving record',
    'parkingCard': 'Smart Parking Assistant',
    'parkingDescription': 'Find and navigate to available parking spots',
    'emergencyCard': 'Emergency Services',
    'emergencyDescription': 'Quick access to emergency contacts and services',
    'navigationCard': 'Smart Navigation',
    'navigationDescription': 'Get optimized routes with real-time traffic updates',
    'communityCard': 'Community Features',
    'communityDescription': 'Connect with local drivers and share experiences',

    // Notifications
    'notifications.title': 'Report Notifications',
    'notifications.noReports': 'No reports received yet',
    'notifications.newReport': 'New Report Received',
    'notifications.newReportDesc': 'You have received a new report about your vehicle.',
    'notifications.resolved': 'Resolved',
    'notifications.pending': 'Pending',
    'notifications.vehicle': 'Vehicle',
    'notifications.reportDetails': 'Report Details',
    'notifications.noComment': 'No comment',
    'notifications.date': 'Date',
    'notifications.evidencePhoto': 'Evidence Photo',
    'notifications.rateReport': 'Rate this report (required)',
    'notifications.yourResponse': 'Your Response (Optional)',
    'notifications.responsePlaceholder': 'Add your response to this report...',
    'notifications.close': 'Close',
    'notifications.markResolved': 'Mark as Resolved',
    'notifications.resolving': 'Resolving...',
    'notifications.reportResolved': 'This report was resolved on',
    'notifications.ratingRequired': 'Rating Required',
    'notifications.ratingRequiredDesc': 'Please provide a rating to resolve the report.',
    'notifications.resolveError': 'Failed to resolve report. Please try again.',
    'notifications.reportResolvedTitle': 'Report Resolved',
    'notifications.reportResolvedDesc': 'Thank you for your response. The report has been marked as resolved.',
    'notifications': 'Notifications',
    'clearAll': 'Clear All',
    'markAsRead': 'Mark as Read',
    'noNotifications': 'No notifications',
    'newNotification': 'New notification received',
    'notificationMarkedRead': 'Notification marked as read',
    'allNotificationsCleared': 'All notifications cleared',
    'reportSubmitted': 'Report submitted successfully',

    // Report types
    'wrongParking': 'Wrong Parking',
    'weatherIssue': 'Weather Issue',
    'roadDamage': 'Road Damage',
    'trafficLight': 'Traffic Light',
    'accident': 'Accident',
    'other': 'Other',

    // Report modal
    'reportProblem': 'Report Problem',
    'report.chooseMethod': 'Choose reporting method',
    'report.scanQRCode': 'Scan QR Code',
    'report.insertPlateNumber': 'Insert Plate Number',
    'report.insertPlateNumberDesc': 'Manually enter a vehicle\'s plate number to report an issue',
    'report.scanQRCodeDesc': 'Use your camera to scan a vehicle\'s QR code and report an issue',
    'report.whatProblem': 'What problem would you like to report?',
    'selectReportType': 'Select report type',
    'description': 'Description',
    'descriptionPlaceholder': 'Describe the issue in detail...',
    'attachPhoto': 'Attach Photo',
    'cancel': 'Cancel',
    'submit': 'Submit',
    'notifications.details': 'Details',

    // Profile Modal
    'profile': 'Profile',
    'personal': 'Personal',
    'vehicles': 'Vehicles',
    'settings': 'Settings',
    'personalInfo': 'Personal Information',
    'firstName': 'First Name',
    'lastName': 'Last Name',
    'phone': 'Phone',
    'firstNamePlaceholder': 'Enter your first name',
    'lastNamePlaceholder': 'Enter your last name',
    'phonePlaceholder': 'Enter your phone number',
    'saveChanges': 'Save Changes',
    'profileUpdated': 'Profile updated successfully',
    'myVehicles': 'My Vehicles',
    'addVehicle': 'Add Vehicle',
    'noVehicles': 'No vehicles added yet',
    'addFirstVehicle': 'Add your first vehicle to get started',
    'brand': 'Brand',
    'model': 'Model',
    'year': 'Year',
    'licensePlate': 'License Plate',
    'color': 'Color',
    'brandPlaceholder': 'e.g., Toyota',
    'modelPlaceholder': 'e.g., Camry',
    'yearPlaceholder': 'e.g., 2020',
    'licensePlatePlaceholder': 'e.g., ABC-123',
    'colorPlaceholder': 'e.g., Blue',
    'vehicleAdded': 'Vehicle added successfully',
    'appSettings': 'App Settings',
    'language': 'Language',
    'theme': 'Theme',
    'pushNotifications': 'Push notifications',
    'emailNotifications': 'Email notifications',
    'smsNotifications': 'SMS notifications',
    'privacySecurity': 'Privacy & Security',
    'shareLocation': 'Share location data',
    'shareUsageData': 'Share usage analytics',
    'logout': 'Logout',
    'confirmLogout': 'Are you sure you want to logout?',

    // Admin
    'adminLogin': 'Admin Login',
    'welcomeAdmin': 'Welcome, Admin',
    'adminLoginDescription': 'Please enter your admin credentials to access the dashboard',
    'emailPlaceholder': 'Enter your admin email',
    'passwordPlaceholder': 'Enter your admin password',
    'signInAsAdmin': 'Sign in as Admin',
    'forgotPassword': 'Forgot your password?',

    // Report Modal - Full translations
    'report.title': 'Report Problem',
    'report.selectProblem': 'Select the type of problem you want to report:',
    'report.wrongParking': 'Wrong Parking',
    'report.wrongParkingDesc': 'Vehicle parked in unauthorized or inappropriate location',
    'report.carProblem': 'Car Problem',
    'report.carProblemDesc': 'Mechanical issues, breakdown, or vehicle malfunction',
    'report.forgottenLights': 'Forgotten Lights',
    'report.forgottenLightsDesc': 'Vehicle with lights left on, potentially draining battery',
    'report.weatherIssue': 'Weather Issue',
    'report.weatherIssueDesc': 'Weather-related problems affecting vehicles or traffic',
    'report.suspiciousActivity': 'Suspicious Activity',
    'report.suspiciousActivityDesc': 'Unusual or concerning behavior around vehicles',
    'report.emergencyEvacuation': 'Emergency Evacuation',
    'report.emergencyEvacuationDesc': 'Emergency situation requiring immediate evacuation',
    'report.vehiclePlateNumber': 'Vehicle Plate Number',
    'report.additionalDetails': 'Additional Details (Optional)',
    'report.photoEvidence': 'Photo Evidence (Optional)',
    'report.takePhoto': 'Take Photo',
    'report.uploadPhoto': 'Upload Photo',
    'report.submitReport': 'Submit Report',
    'report.back': 'Back',
    'report.cancel': 'Cancel',
    'report.plateNumberPlaceholder': 'Enter plate number',
    'report.descriptionPlaceholder': 'Describe what happened...',
    'report.registeredUser': 'Registered User',
    'report.unregisteredVehicle': 'Unregistered Vehicle',
    'report.photoHelp': 'Take a photo or upload evidence to support your report',
    'report.submitting': 'Submitting...',

    // Landing Page - Hero Section
    'hero.badge': 'Complete Driver Assistance Platform',
    'hero.title.part1': 'All-in-One',
    'hero.title.part2': 'Driver Platform',
    'hero.subtitle': 'Connect, report, navigate, communicate, and manage everything driver-related in one powerful platform. From QR codes to emergency services, community chat to penalty management.',
    'hero.getStarted': 'Get Started Now',
    'hero.exploreFeaturesBtn': 'Explore Features',
    'hero.stats.drivers': 'Active Drivers',
    'hero.stats.reports': 'Reports Filed',
    'hero.stats.emergency': 'Emergency Calls',
    'hero.stats.community': 'Community Members',
    'hero.feature1': 'Real-time Support',
    'hero.feature2': 'QR Code Integration',
    'hero.feature3': 'Smart Navigation',

    // Features Section
    'features.badge': 'Core Features',
    'features.title.part1': 'Everything You Need',
    'features.title.part2': 'In One Platform',
    'features.subtitle': 'From emergency assistance to community features, our platform provides comprehensive tools for modern drivers.',
    'features.qr.title': 'QR Code Generation',
    'features.qr.description': 'Generate unique QR codes for your vehicle profile that can be scanned by other drivers or emergency services.',
    'features.reports.title': 'Report Issues',
    'features.reports.description': 'Quickly report parking violations, car problems, or other issues to help the community stay informed.',
    'features.emergency.title': 'Emergency Services',
    'features.emergency.description': 'Direct access to emergency services with location sharing and incident documentation.',
    'features.navigation.title': 'Smart Navigation',
    'features.navigation.description': 'Interactive maps with real-time traffic updates and optimized routing for better journeys.',
    'features.security.title': 'Security & Privacy',
    'features.security.description': 'Your data is protected with enterprise-grade security and privacy controls you can trust.',
    'features.community.title': 'Driver Community',
    'features.community.description': 'Connect with other drivers, share experiences, and build a supportive driving community.',

    // Advanced Features Section
    'advanced.badge': 'Advanced Features',
    'advanced.title.part1': 'Professional Tools',
    'advanced.title.part2': 'For Modern Drivers',
    'advanced.subtitle': 'Advanced management tools and integrations designed for professional drivers and fleet managers.',
    'advanced.payment.title': 'Payment Management',
    'advanced.payment.description': 'Secure payment processing for parking fees, tolls, and other driving-related expenses.',
    'advanced.payment.stats': '99.9% Uptime',
    'advanced.penalty.title': 'Penalty Tracking',
    'advanced.penalty.description': 'Track and manage traffic violations, fines, and penalty payments in one place.',
    'advanced.penalty.stats': 'Real-time',
    'advanced.vehicle.title': 'Vehicle Management',
    'advanced.vehicle.description': 'Comprehensive vehicle profiles with maintenance tracking and documentation.',
    'advanced.vehicle.stats': 'Multi-vehicle',
    'advanced.language.title': 'Multi-language Support',
    'advanced.language.description': 'Platform available in multiple languages for global accessibility.',
    'advanced.language.stats': '3 Languages',
    'advanced.interface.title': 'Dark/Light Mode',
    'advanced.interface.description': 'Customizable interface themes for optimal viewing in any lighting condition.',
    'advanced.interface.stats': 'Adaptive',
    'advanced.notifications.title': 'Smart Notifications',
    'advanced.notifications.description': 'Intelligent alerts and notifications for important driving-related updates.',
    'advanced.notifications.stats': 'Push/Email',

    // Q&A Section
    'qa.badge': 'Frequently Asked Questions',
    'qa.title': 'Questions & Answers',
    'qa.subtitle': 'Find answers to common questions about our platform and features.',
    'qa.question1': 'How do I generate a QR code for my vehicle?',
    'qa.answer1': 'Simply go to your dashboard, click on the QR Code card, fill in your vehicle information, and generate your unique QR code. You can then print it or save it digitally.',
    'qa.question2': 'What should I do in case of an emergency?',
    'qa.answer2': 'Use the Emergency Services feature on your dashboard. Select the appropriate service (Police, Ambulance, Fire), add any relevant information, and the system will help you contact emergency services with your location.',
    'qa.question3': 'How does the reporting system work?',
    'qa.answer3': 'You can report various issues like wrong parking, car problems, or weather issues. Simply select the Report Problem option, choose the issue type, provide details, and optionally attach a photo.',
    'qa.question4': 'Is my personal data secure?',
    'qa.answer4': 'Yes, we use enterprise-grade security measures to protect your data. All information is encrypted and we follow strict privacy guidelines to ensure your data remains secure.',
    'qa.question5': 'Can I use the platform in multiple languages?',
    'qa.answer5': 'Yes, our platform supports English, Romanian, and Russian. You can change the language in your settings or using the language toggle in the navigation.',
    'qa.question6': 'How do I connect with other drivers?',
    'qa.answer6': 'Use the Community features to search for other drivers, send friend requests, and start conversations. You can find drivers by name or vehicle details and build a network of fellow drivers.',

    // Footer
    'footer.brand': 'DAP',
    'footer.subtitle': 'Drivers Assistance Platform',
    'footer.description': 'Connecting drivers worldwide with innovative safety features, emergency services, and community-driven reporting systems.',
    'footer.contact': 'Contact Us',
    'footer.copyright': '© 2025 DAP - Drivers Assistance Platform. All rights reserved.',
    'footer.tagline': 'Built with safety and innovation in mind.',

    
    // Mobile Navigation
    'mobile.myProfile': 'My Profile',
    'mobile.quickReport': 'Quick Report',

    // Common
    'language.english': 'English',
    'language.romanian': 'Română',
    'language.russian': 'Русский',
    'language.turkish': 'Türkçe',
    'language.moldova': 'Moldova',
  },
  ro: {

 //bug fix
    'community.message': 'Mesaj',
    'community.friends': 'Prieteni',
    'community.searchUsers': 'Caută utilizatori după nume sau detalii ale vehiculului',
    'community.requests': 'Cereri',
    'community.blocked': 'Blocat',
    'mobile.signOut': 'Deconectare',

    // Navigation
    'nav.welcome': 'Bun venit',
    'nav.profile': 'Profil',
    'nav.menu': 'Meniu',
    'nav.home': 'Acasă',
    'nav.dashboard': 'Panou de control',
    'nav.signOut': 'Deconectare',
    'nav.report': 'Raportează',
    'nav.emergency': 'Urgență',
    'nav.navigation': 'Navigare',
    'nav.qrCode': 'Cod QR',
    'nav.title': 'Platforma de Asistență a Șoferilor',
    'nav.admin'  : 'Admin',

     //Friend Modal
    'friends.title':'Prieteni',
    'friends.description':'Descriere',

    // Auth page
    'auth.hello': 'Salut!',
    'auth.subtitle': 'Conectează-te pentru a accesa panoul de șofer',
    'auth.welcomeTo': 'Bun venit la',
    'auth.platformName': 'Platforma DAP',
    'auth.tagline': 'Companionul tău inteligent de condus pentru călătorii mai sigure și mai inteligente',
    'auth.smartNavigation': 'Navigare Inteligentă',
    'auth.emergencySupport': 'Suport de Urgență',
    'auth.communityDriven': 'Condus de Comunitate',
    'auth.backToHome': 'Înapoi la pagina principală',
    'auth.alreadyHaveAccount': 'Ai deja un cont?',
    'auth.signIn': 'Conectare',
    'auth.getStarted': 'Începe',
    'auth.email': 'Email',
    'auth.password': 'Parolă',
    'auth.createPassword': 'Creează o parolă',
    'auth.confirmPassword': 'Confirmă parola',
    'auth.emailRequired': 'Email-ul este necesar',
    'auth.passwordRequired': 'Parola este necesară',
    'auth.passwordMinLength': 'Parola trebuie să aibă cel puțin 6 caractere',
    'auth.confirmPasswordRequired': 'Te rugăm să confirmi parola',
    'auth.signingIn': 'Se conectează...',
    'auth.creatingAccount': 'Se creează contul...',
    'auth.createAccount': 'Creează cont',
    'auth.welcomeBack': 'Bun venit înapoi',
    'auth.signInToContinue': 'Conectează-te la contul tău pentru a continua',
    'auth.joinCommunity': 'Alătură-te comunității noastre pentru a începe',
    'auth.dontHaveAccount': 'Nu ai un cont?',
    'auth.signUp': 'Înregistrează-te',
    'auth.signInWithEmail': 'Conectează-te cu email',
    'auth.signUpWithEmail': 'Înregistrează-te cu email',

    // Dashboard
    'dashboard.title': 'Asistență pentru Șoferi',
    'dashboard.welcome': 'Bun venit',
    'dashboard.subtitle': 'Alege o opțiune de mai jos pentru a începe',
    'menu': 'Meniu',
    'home': 'Acasă',
    'qrCode': 'Cod QR',

    // Profile Modal
    'profile.title': 'Profilul Meu',
    'profile.profileTab': 'Profil',
    'profile.carsTab': 'Mașini',
    'profile.servicesTab': 'Servicii',
    'profile.accountTab': 'Cont',
    'profile.personalInfo': 'Informații Personale',
    'profile.changePhoto': 'Schimbă Fotografia',
    'profile.firstName': 'Prenume',
    'profile.lastName': 'Nume',
    'profile.phoneNumber': 'Număr de Telefon',
    'profile.saveProfile': 'Salvează Profilul',
    'profile.noCarsRegistered': 'Nu sunt mașini înregistrate',
    'profile.addCar': 'Adaugă Mașină',
    'profile.noServicesRecorded': 'Nu sunt servicii înregistrate',
    'profile.addService': 'Adaugă Serviciu',
    'profile.camera': 'Cameră',
    'profile.upload': 'Încarcă',
    'profile.firstNamePlaceholder': 'Introdu prenumele',
    'profile.lastNamePlaceholder': 'Introdu numele',
    'profile.phoneNumberPlaceholder': 'Introdu numărul de telefon',
    'profile.myCars': 'Mașinile Mele',
    'profile.noCarsAdded': 'Nu sunt mașini adăugate încă',
    'profile.addNewCar': 'Adaugă Mașină Nouă',
    'profile.carName': 'Numele Mașinii',
    'profile.carNamePlaceholder': 'ex. Toyota-ul meu',
    'profile.model': 'Model',
    'profile.modelPlaceholder': 'ex. Camry',
    'profile.plateNumber': 'Numărul de Înmatriculare',
    'profile.plateNumberPlaceholder': 'ex. ABC-123',
    'profile.carPhoneNumber': 'Numărul de Telefon al Mașinii',
    'profile.carPhonePlaceholder': 'Număr de contact de urgență',
    'profile.cancel': 'Anulează',
    'profile.myServices': 'Serviciile Mele',
    'profile.noServicesAdded': 'Nu sunt servicii adăugate încă',
    'profile.accountSettings': 'Setări Cont',
    'profile.email': 'Email',
    'profile.change': 'Schimbă',
    'profile.password': 'Parolă',
    'profile.passwordDesc': 'Ultima modificare acum 30 de zile',
    'profile.deleteAccount': 'Șterge Contul',
    'profile.deleteAccountDesc': 'Șterge permanent contul și toate datele',
    'profile.delete': 'Șterge',
    'profile.qrCode': 'Cod QR',
    'profile.qrCodeDesc': 'Nu a fost generat încă un cod QR',
    'profile.generateQR': 'Generează Cod QR',
    'profile.updateQR': 'Actualizează Cod QR',
    'profile.downloadQR': 'Descarcă',
    'profile.uploading': 'Se încarcă...',
    'profile.avatarUpdated': 'Avatar Actualizat',
    'profile.avatarUpdatedDesc': 'Fotografia de profil a fost actualizată cu succes.',
    'profile.uploadFailed': 'Încărcarea a Eșuat',
    'profile.uploadFailedDesc': 'Nu s-a putut încărca imaginea. Încearcă din nou.',
    'profile.profileSaved': 'Profil Salvat',
    'profile.profileSavedDesc': 'Profilul tău a fost actualizat cu succes.',
    'profile.carAdded': 'Mașină Adăugată',
    'profile.carAddedDesc': 'Mașina ta a fost adăugată cu succes.',

    // Emergency Modal
     'emergency.title': 'Servicii de Urgență',
    'emergency.selectService': 'Selectează un serviciu de urgență de mai jos. Poți adăuga informații suplimentare înainte de a efectua apelul.',
    'emergency.services.ambulance': 'Ambulanță',
    'emergency.services.police': 'Poliție',
    'emergency.services.fire': 'Pompieri',
    'emergency.services.ambulanceDesc': 'Urgențe medicale și incidente legate de sănătate',
    'emergency.services.policeDesc': 'Activități criminale, accidente și probleme de securitate',
    'emergency.services.fireDesc': 'Incendii, scurgeri de gaz și operațiuni de salvare',
    'emergency.importantNotice': 'Notificare Importantă',
    'emergency.onlyGenuineEmergencies': 'Acestea sunt numere de contact pentru urgențe. Te rugăm să le folosești doar pentru urgențe reale. Pentru probleme non-urgente, contactează serviciile non-urgente adecvate.',
    'emergency.additionalInfo': 'Informații Suplimentare (Opțional)',
    'emergency.changeService': 'Schimbă Serviciul',
    'emergency.addDetails': 'Adaugă Detalii',
    'emergency.additionalInfoPlaceholder': 'Furnizează orice informație suplimentară care ar putea ajuta echipele de intervenție...',
    'emergency.attachImage': 'Atașează Imagine (Opțional)',
    'emergency.uploadImage': 'Încarcă Imagine',
    'emergency.chooseImage': 'Alege Imagine',
    'emergency.dialerNote': 'Vei fi redirecționat către aplicația de apelare a telefonului tău cu numărul de urgență completat. Te rugăm să te asiguri că ai o conexiune stabilă înainte de a continua.',
    'emergency.back': 'Înapoi',
    'emergency.call': 'Sună',

        // Navigation Modal
    'navigation.title': 'Navigare',
    'navigation.getDirections': 'Obține indicații către destinația ta folosind harta de mai jos. Selectează o locație pentru a începe navigarea.',
    'navigation.clickOnMap': 'Selectează Locația',
    'navigation.mapUnavailable': 'Harta nu este disponibilă în această demonstrație.',
    'navigation.findPlaces': 'Găsește locuri după nume sau adresă',
    'navigation.nearbyLocations': 'Locații din apropiere',
    'navigation.trafficInfo': 'Informații de trafic în timp real',
    'navigation.currentTraffic': 'Trafic Curent',
    'navigation.savedRoutes': 'Rute Salvate',
    'navigation.frequentDestinations': 'Destinații Frecvente',

   //Penalty Management
    'penalties.myPenalties': 'Penalitățile Mele',
    'penalties.activePenalties': 'Penalități Active',
    'penalties.totalPoints': 'Total Puncte',
    'penalties.unpaidFines': 'Amenzi Neplătite',
    'penalties.addPenalty': 'Adaugă Penalitate',

    // Service Management
    'service.title': 'Managementul Serviciilor',
    'service.subtitle': 'Gestionează serviciile vehiculului, înregistrările de întreținere și datele importante.',
    'service.addService': 'Adaugă Serviciu',
    'service.type': 'Tipul Serviciului',
    'service.description': 'Descriere',
    'service.price': 'Preț',
    'service.date': 'Data Serviciului',
    'service.expiryDate': 'Data Expirării',
    'service.expires': 'Expiră',

    // Cards
    'cards.reportProblem.title': 'Raportează Problemă',
    'cards.reportProblem.description': 'Raportează probleme cu vehiculele sau condițiile drumului către alți șoferi',
    'cards.qrCode.title': 'Generează Cod QR',
    'cards.qrCode.description': 'Creează un cod QR cu informațiile profilului și mașinii tale',
    'cards.emergency.title': 'Urgență',
    'cards.emergency.description': 'Acces rapid la serviciile de urgență cu comentarii și imagini opționale',
    'cards.navigation.title': 'Navigare',
    'cards.navigation.description': 'Navigare interactivă pe hartă pentru a te ajuta să îți găsești drumul',
    'cards.service.title': 'Service',
    'cards.service.description': 'Gestionează serviciile vehiculului, asigurarea și evidențele de întreținere',
    'cards.community.title': 'Comunitate',
    'cards.community.description': 'Conectează-te cu alți șoferi, adaugă prieteni și începe conversații',
    'cards.penalties.title': 'Gestionarea Penalităților',
    'cards.penalties.description': 'Vizualizează penalitățile rutiere active și inactive, statusul plății și gestionează dosarul de condus',
    'parkingCard': 'Asistent Parcare Inteligentă',
    'parkingDescription': 'Găsește și navighează către locurile de parcare disponibile',
    'emergencyCard': 'Servicii de Urgență',
    'emergencyDescription': 'Acces rapid la contacte și servicii de urgență',
    'navigationCard': 'Navigație Inteligentă',
    'navigationDescription': 'Obține rute optimizate cu actualizări de trafic în timp real',
    'communityCard': 'Funcții Comunitate',
    'communityDescription': 'Conectează-te cu șoferii locali și împarte experiențele',

    // Notifications
    'notifications.title': 'Notificări Rapoarte',
    'notifications.noReports': 'Nu au fost primite rapoarte încă',
    'notifications.newReport': 'Raport Nou Primit',
    'notifications.newReportDesc': 'Ai primit un raport nou despre vehiculul tău.',
    'notifications.resolved': 'Rezolvat',
    'notifications.pending': 'În așteptare',
    'notifications.vehicle': 'Vehicul',
    'notifications.reportDetails': 'Detalii Raport',
    'notifications.noComment': 'Niciun comentariu',
    'notifications.date': 'Data',
    'notifications.evidencePhoto': 'Fotografie Dovadă',
    'notifications.rateReport': 'Evaluează acest raport (obligatoriu)',
    'notifications.yourResponse': 'Răspunsul Tău (Opțional)',
    'notifications.responsePlaceholder': 'Adaugă răspunsul tău la acest raport...',
    'notifications.close': 'Închide',
    'notifications.markResolved': 'Marchează ca Rezolvat',
    'notifications.resolving': 'Se rezolvă...',
    'notifications.reportResolved': 'Acest raport a fost rezolvat pe',
    'notifications.ratingRequired': 'Evaluare Necesară',
    'notifications.ratingRequiredDesc': 'Te rugăm să oferi o evaluare pentru a rezolva raportul.',
    'notifications.resolveError': 'Nu s-a putut rezolva raportul. Încearcă din nou.',
    'notifications.reportResolvedTitle': 'Raport Rezolvat',
    'notifications.reportResolvedDesc': 'Mulțumim pentru răspuns. Raportul a fost marcat ca rezolvat.',
    'notifications': 'Notificări',
    'clearAll': 'Șterge Tot',
    'markAsRead': 'Marchează ca Citit',
    'noNotifications': 'Nicio notificare',
    'newNotification': 'Notificare nouă primită',
    'notificationMarkedRead': 'Notificare marcată ca citită',
    'allNotificationsCleared': 'Toate notificările au fost șterse',
    'reportSubmitted': 'Raportul a fost trimis cu succes',

    // Report types
    'wrongParking': 'Parcare Greșită',
    'weatherIssue': 'Problemă Meteorologică',
    'roadDamage': 'Deteriorare Drum',
    'trafficLight': 'Semafor',
    'accident': 'Accident',
    'other': 'Altele',

    // Report modal
    'reportProblem': 'Raportează Problemă',
    'report.chooseMethod': 'Alege metoda de raportare',
    'report.scanQRCode': 'Scanează Cod QR',
    'report.scanQRCodeDesc': 'Folosește camera pentru a scana codul QR al unui vehicul și raportează o problemă',
    'report.insertPlateNumber': 'Introdu Numărul de Înmatriculare',
    'report.insertPlateNumberDesc': 'Introdu manual numărul de înmatriculare al unui vehicul pentru a raporta o problemă',
    'selectReportType': 'Selectează tipul raportului',
    'report.whatProblem': 'Ce problemă dorești să raportezi?',
    'description': 'Descriere',
    'descriptionPlaceholder': 'Descrie problema în detaliu...',
    'attachPhoto': 'Atașează Fotografie',
    'cancel': 'Anulează',
    'submit': 'Trimite',
    'notifications.details': 'Detalii',

    // Profile Modal
    'profile': 'Profil',
    'personal': 'Personal',
    'vehicles': 'Vehicule',
    'settings': 'Setări',
    'personalInfo': 'Informații Personale',
    'firstName': 'Prenume',
    'lastName': 'Nume',
    'phone': 'Telefon',
    'firstNamePlaceholder': 'Introdu prenumele',
    'lastNamePlaceholder': 'Introdu numele',
    'phonePlaceholder': 'Introdu numărul de telefon',
    'saveChanges': 'Salvează Modificările',
    'profileUpdated': 'Profilul a fost actualizat cu succes',
    'myVehicles': 'Vehiculele Mele',
    'addVehicle': 'Adaugă Vehicul',
    'noVehicles': 'Niciun vehicul adăugat încă',
    'addFirstVehicle': 'Adaugă primul tău vehicul pentru a începe',
    'brand': 'Marcă',
    'model': 'Model',
    'year': 'An',
    'licensePlate': 'Număr de Înmatriculare',
    'color': 'Culoare',
    'brandPlaceholder': 'ex. Toyota',
    'modelPlaceholder': 'ex. Camry',
    'yearPlaceholder': 'ex. 2020',
    'licensePlatePlaceholder': 'ex. ABC-123',
    'colorPlaceholder': 'ex. Albastru',
    'vehicleAdded': 'Vehiculul a fost adăugat cu succes',
    'appSettings': 'Setări Aplicație',
    'language': 'Limbă',
    'theme': 'Temă',
    'pushNotifications': 'Notificări push',
    'emailNotifications': 'Notificări email',
    'smsNotifications': 'Notificări SMS',
    'privacySecurity': 'Confidențialitate și Securitate',
    'shareLocation': 'Partajează datele de locație',
    'shareUsageData': 'Partajează analize de utilizare',
    'logout': 'Deconectare',
    'confirmLogout': 'Ești sigur că vrei să te deconectezi?',

    // Admin
    'adminLogin': 'Conectare Administrator',
    'welcomeAdmin': 'Bun venit, Administrator',
    'adminLoginDescription': 'Vă rugăm să introduceți datele de administrator pentru a accesa panoul de control',
    'emailPlaceholder': 'Introduceți emailul de administrator',
    'passwordPlaceholder': 'Introduceți parola de administrator',
    'signInAsAdmin': 'Conectați-vă ca Administrator',
    'forgotPassword': 'Ați uitat parola?',

    // Report Modal - Full translations
    'report.title': 'Raportează Problemă',
    'report.selectProblem': 'Selectează tipul problemei pe care vrei să o raportezi:',
    'report.wrongParking': 'Parcare Greșită',
    'report.wrongParkingDesc': 'Vehicul parcat în locație neautorizată sau inadecvată',
    'report.carProblem': 'Problemă Auto',
    'report.carProblemDesc': 'Probleme mecanice, defecțiuni sau malfuncții ale vehiculului',
    'report.forgottenLights': 'Lumini Uitate',
    'report.forgottenLightsDesc': 'Vehicul cu luminile lăsate aprinse, care pot descărca bateria',
    'report.weatherIssue': 'Problemă Meteorologică',
    'report.weatherIssueDesc': 'Probleme legate de vreme care afectează vehiculele sau traficul',
    'report.suspiciousActivity': 'Activitate Suspectă',
    'report.suspiciousActivityDesc': 'Comportament neobișnuit sau îngrijorător în jurul vehiculelor',
    'report.emergencyEvacuation': 'Evacuare de Urgență',
    'report.emergencyEvacuationDesc': 'Situație de urgență care necesită evacuare imediată',
    'report.vehiclePlateNumber': 'Numărul de Înmatriculare al Vehiculului',
    'report.additionalDetails': 'Detalii Suplimentare (Opțional)',
    'report.photoEvidence': 'Dovadă Foto (Opțional)',
    'report.takePhoto': 'Fă o Fotografie',
    'report.uploadPhoto': 'Încarcă Fotografie',
    'report.submitReport': 'Trimite Raportul',
    'report.back': 'Înapoi',
    'report.cancel': 'Anulează',
    'report.plateNumberPlaceholder': 'Introdu numărul de înmatriculare',
    'report.descriptionPlaceholder': 'Descrie ce s-a întâmplat...',
    'report.registeredUser': 'Utilizator Înregistrat',
    'report.unregisteredVehicle': 'Vehicul Neînregistrat',
    'report.photoHelp': 'Fă o fotografie sau încarcă dovezi pentru a susține raportul tău',
    'report.submitting': 'Se trimite...',

    // Landing Page - Hero Section
    'hero.badge': 'Platformă Completă de Asistență pentru Șoferi',
    'hero.title.part1': 'Totul într-o Singură',
    'hero.title.part2': 'Platformă pentru Șoferi',
    'hero.subtitle': 'Conectează-te, raportează, navighează, comunică și gestionează tot ce ține de condus într-o singură platformă puternică. De la coduri QR la servicii de urgență, chat comunitar la gestionarea penalităților.',
    'hero.getStarted': 'Începe Acum',
    'hero.exploreFeaturesBtn': 'Explorează Funcțiile',
    'hero.stats.drivers': 'Șoferi Activi',
    'hero.stats.reports': 'Rapoarte Depuse',
    'hero.stats.emergency': 'Apeluri de Urgență',
    'hero.stats.community': 'Membri ai Comunității',
    'hero.feature1': 'Suport în Timp Real',
    'hero.feature2': 'Integrare Cod QR',
    'hero.feature3': 'Navigare Inteligentă',

    // Features Section
    'features.badge': 'Funcții de Bază',
    'features.title.part1': 'Tot Ce Ai Nevoie',
    'features.title.part2': 'Într-o Singură Platformă',
    'features.subtitle': 'De la asistență de urgență la funcții de comunitate, platforma noastră oferă instrumente cuprinzătoare pentru șoferii moderni.',
    'features.qr.title': 'Generare Cod QR',
    'features.qr.description': 'Generează coduri QR unice pentru profilul vehiculului tău care pot fi scanate de alți șoferi sau servicii de urgență.',
    'features.reports.title': 'Raportează Probleme',
    'features.reports.description': 'Raportează rapid încălcările de parcare, problemele auto sau alte probleme pentru a ține comunitatea informată.',
    'features.emergency.title': 'Servicii de Urgență',
    'features.emergency.description': 'Acces direct la serviciile de urgență cu partajarea locației și documentarea incidentelor.',
    'features.navigation.title': 'Navigare Inteligentă',
    'features.navigation.description': 'Hărți interactive cu actualizări de trafic în timp real și rutare optimizată pentru călătorii mai bune.',
    'features.security.title': 'Securitate și Confidențialitate',
    'features.security.description': 'Datele tale sunt protejate cu securitate de nivel enterprise și controale de confidențialitate în care poți avea încredere.',
    'features.community.title': 'Comunitatea Șoferilor',
    'features.community.description': 'Conectează-te cu alți șoferi, împărtășește experiențe și construiește o comunitate de condus care să te susțină.',

    // Advanced Features Section
    'advanced.badge': 'Funcții Avansate',
    'advanced.title.part1': 'Instrumente Profesionale',
    'advanced.title.part2': 'Pentru Șoferii Moderni',
    'advanced.subtitle': 'Instrumente avansate de management și integrări concepute pentru șoferii profesioniști și managerii de flote.',
    'advanced.payment.title': 'Gestionarea Plăților',
    'advanced.payment.description': 'Procesare securizată a plăților pentru taxele de parcare, taxe de drum și alte cheltuieli legate de condus.',
    'advanced.payment.stats': '99.9% Timp de funcționare',
    'advanced.penalty.title': 'Urmărirea Penalităților',
    'advanced.penalty.description': 'Urmărește și gestionează încălcările de trafic, amenzi și plăți de penalități într-un singur loc.',
    'advanced.penalty.stats': 'Timp real',
    'advanced.vehicle.title': 'Gestionarea Vehiculelor',
    'advanced.vehicle.description': 'Profile complete ale vehiculelor cu urmărirea întreținerii și documentația.',
    'advanced.vehicle.stats': 'Multi-vehicul',
    'advanced.language.title': 'Suport Multi-limbă',
    'advanced.language.description': 'Platforma disponibilă în mai multe limbi pentru accesibilitate globală.',
    'advanced.language.stats': '3 Limbi',
    'advanced.interface.title': 'Mod Întunecat/Luminos',
    'advanced.interface.description': 'Teme personalizabile ale interfeței pentru vizualizare optimă în orice condiție de iluminare.',
    'advanced.interface.stats': 'Adaptiv',
    'advanced.notifications.title': 'Notificări Inteligente',
    'advanced.notifications.description': 'Alerte inteligente și notificări pentru actualizări importante legate de condus.',
    'advanced.notifications.stats': 'Push/Email',

    // Q&A Section
    'qa.badge': 'Întrebări Frecvente',
    'qa.title': 'Întrebări și Răspunsuri',
    'qa.subtitle': 'Găsește răspunsuri la întrebări comune despre platforma și funcțiile noastre.',
    'qa.question1': 'Cum generez un cod QR pentru vehiculul meu?',
    'qa.answer1': 'Pur și simplu mergi la panoul tău de control, click pe cardul Cod QR, completează informațiile vehiculului și generează codul QR unic. Apoi îl poți imprima sau salva digital.',
    'qa.question2': 'Ce ar trebui să fac în caz de urgență?',
    'qa.answer2': 'Folosește funcția Servicii de Urgență din panoul tău de control. Selectează serviciul corespunzător (Poliție, Ambulanță, Pompieri), adaugă informații relevante, iar sistemul te va ajuta să contactezi serviciile de urgență cu locația ta.',
    'qa.question3': 'Cum funcționează sistemul de raportare?',
    'qa.answer3': 'Poți raporta diverse probleme precum parcare greșită, probleme auto sau probleme meteorologice. Pur și simplu selectează opțiunea Raportează Problemă, alege tipul problemei, oferă detalii și opțional atașează o fotografie.',
    'qa.question4': 'Sunt datele mele personale sigure?',
    'qa.answer4': 'Da, folosim măsuri de securitate de nivel enterprise pentru a-ți proteja datele. Toate informațiile sunt criptate și urmărim ghiduri stricte de confidențialitate pentru a ne asigura că datele tale rămân sigure.',
    'qa.question5': 'Pot folosi platforma în mai multe limbi?',
    'qa.answer5': 'Da, platforma noastră suportă engleză, română și rusă. Poți schimba limba în setările tale sau folosind comutatorul de limbă din navigare.',
    'qa.question6': 'Cum mă conectez cu alți șoferi?',
    'qa.answer6': 'Folosește funcțiile Comunitate pentru a căuta alți șoferi, trimite cereri de prietenie și începe conversații. Poți găsi șoferi după nume sau detalii vehicul și construi o rețea de șoferi colegi.',

    // Footer
    'footer.brand': 'DAP',
    'footer.subtitle': 'Platforma de Asistență pentru Șoferi',
    'footer.description': 'Conectând șoferii din întreaga lume cu funcții inovatoare de siguranță, servicii de urgență și sisteme de raportare conduse de comunitate.',
    'footer.contact': 'Contactează-ne',
    'footer.copyright': '© 2025 DAP - Platforma de Asistență pentru Șoferi. Toate drepturile rezervate.',
    'footer.tagline': 'Construit cu siguranță și inovare în minte.',

    // Mobile Navigation
    'mobile.myProfile': 'Profilul Meu',
    'mobile.quickReport': 'Raport Rapid',

    // Common
    'language.english': 'English',
    'language.romanian': 'Română',
    'language.russian': 'Русский',
    'language.turkish': 'Türkçe',
    'language.moldova': 'Moldova',
    
  },

  ru: {
 //bug fix
    'community.message': 'Сообщение',
    'mobile.signOut': 'Выйти',

    // Navigation
    'nav.welcome': 'Добро пожаловать',
    'nav.profile': 'Профиль',
    'nav.menu': 'Меню',
    'nav.home': 'Главная',
    'nav.dashboard': 'Панель управления',
    'nav.signOut': 'Выйти',
    'nav.report': 'Сообщить',
    'nav.emergency': 'Экстренная помощь',
    'nav.navigation': 'Навигация',
    'nav.qrCode': 'QR-код',
    'nav.title': 'Платформа для водителей',
    'nav.admin'  : 'Админ',

     //Friend Modal
    'friends.title':'Друзья',
    'friends.description':'Описание',

    // Auth page
    'auth.hello': 'Привет!',
    'auth.subtitle': 'Войдите, чтобы получить доступ к панели водителя',
    'auth.welcomeTo': 'Добро пожаловать в',
    'auth.platformName': 'Платформа DAP',
    'auth.tagline': 'Ваш умный спутник вождения для более безопасных и умных поездок',
    'auth.smartNavigation': 'Умная навигация',
    'auth.emergencySupport': 'Экстренная поддержка',
    'auth.communityDriven': 'Управляемый сообществом',
    'auth.backToHome': 'Вернуться на главную',
    'auth.alreadyHaveAccount': 'Уже есть аккаунт?',
    'auth.signIn': 'Войти',
    'auth.getStarted': 'Начать',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.createPassword': 'Создайте пароль',
    'auth.confirmPassword': 'Подтвердите пароль',
    'auth.emailRequired': 'Email обязателен',
    'auth.passwordRequired': 'Пароль обязателен',
    'auth.passwordMinLength': 'Пароль должен содержать не менее 6 символов',
    'auth.confirmPasswordRequired': 'Пожалуйста, подтвердите пароль',
    'auth.signingIn': 'Вход в систему...',
    'auth.creatingAccount': 'Создание аккаунта...',
    'auth.createAccount': 'Создать аккаунт',
    'auth.welcomeBack': 'Добро пожаловать',
    'auth.signInToContinue': 'Войдите в свою учетную запись, чтобы продолжить',
    'auth.joinCommunity': 'Присоединяйтесь к нашему сообществу, чтобы начать',
    'auth.dontHaveAccount': 'У вас нет аккаунта?',
    'auth.signUp': 'Зарегистрироваться',
    'auth.signInWithEmail': 'Войти через email',
    'auth.signUpWithEmail': 'Зарегистрироваться через email',

    // Dashboard
    'dashboard.title': 'Помощь водителям',
    'dashboard.welcome': 'Добро пожаловать',
    'dashboard.subtitle': 'Выберите опцию ниже, чтобы начать',
    'menu': 'Меню',
    'home': 'Главная',
    'qrCode': 'QR код',

    // Profile Modal
    'profile.title': 'Мой Профиль',
    'profile.profileTab': 'Профиль',
    'profile.carsTab': 'Машины',
    'profile.servicesTab': 'Услуги',
    'profile.accountTab': 'Аккаунт',
    'profile.personalInfo': 'Личная Информация',
    'profile.changePhoto': 'Изменить Фото',
    'profile.firstName': 'Имя',
    'profile.lastName': 'Фамилия',
    'profile.phoneNumber': 'Номер Телефона',
    'profile.saveProfile': 'Сохранить Профиль',
    'profile.noCarsRegistered': 'Нет зарегистрированных машин',
    'profile.addCar': 'Добавить Машину',
    'profile.noServicesRecorded': 'Нет записанных услуг',
    'profile.addService': 'Добавить Услугу',
    'profile.camera': 'Камера',
    'profile.upload': 'Загрузить',
    'profile.firstNamePlaceholder': 'Введите ваше имя',
    'profile.lastNamePlaceholder': 'Введите вашу фамилию',
    'profile.phoneNumberPlaceholder': 'Введите номер телефона',
    'profile.myCars': 'Мои Машины',
    'profile.noCarsAdded': 'Машины ещё не добавлены',
    'profile.addNewCar': 'Добавить Новую Машину',
    'profile.carName': 'Название Машины',
    'profile.carNamePlaceholder': 'например, Моя Toyota',
    'profile.model': 'Модель',
    'profile.modelPlaceholder': 'например, Camry',
    'profile.plateNumber': 'Номерной Знак',
    'profile.plateNumberPlaceholder': 'например, ABC-123',
    'profile.carPhoneNumber': 'Номер Телефона Машины',
    'profile.carPhonePlaceholder': 'Экстренный контактный номер',
    'profile.cancel': 'Отмена',
    'profile.myServices': 'Мои Услуги',
    'profile.noServicesAdded': 'Услуги ещё не добавлены',
    'profile.accountSettings': 'Настройки Аккаунта',
    'profile.email': 'Email',
    'profile.change': 'Изменить',
    'profile.password': 'Пароль',
    'profile.passwordDesc': 'Последнее изменение 30 дней назад',
    'profile.deleteAccount': 'Удалить Аккаунт',
    'profile.deleteAccountDesc': 'Навсегда удалить аккаунт и все данные',
    'profile.delete': 'Удалить',
    'profile.qrCode': 'QR Код',
    'profile.qrCodeDesc': 'QR код ещё не создан',
    'profile.generateQR': 'Создать QR Код',
    'profile.updateQR': 'Обновить QR Код',
    'profile.downloadQR': 'Скачать',
    'profile.uploading': 'Загрузка...',
    'profile.avatarUpdated': 'Аватар Обновлён',
    'profile.avatarUpdatedDesc': 'Ваше фото профиля было успешно обновлено.',
    'profile.uploadFailed': 'Загрузка Не Удалась',
    'profile.uploadFailedDesc': 'Не удалось загрузить изображение. Попробуйте снова.',
    'profile.profileSaved': 'Профиль Сохранён',
    'profile.profileSavedDesc': 'Ваш профиль был успешно обновлён.',
    'profile.carAdded': 'Машина Добавлена',
    'profile.carAddedDesc': 'Ваша машина была успешно добавлена.',

    // Emergency Modal
    'emergency.title': 'Экстренная Помощь',
    'emergency.selectService': 'Выберите службу экстренной помощи ниже. Вы можете добавить дополнительную информацию перед звонком.',
    'emergency.services.ambulance': 'Скорая Помощь',
    'emergency.services.police': 'Полиция',
    'emergency.services.fire': 'Пожарная Служба',
    'emergency.services.ambulanceDesc': 'Медицинские неотложные случаи и инциденты, связанные со здоровьем',
    'emergency.services.policeDesc': 'Преступная деятельность, аварии и проблемы безопасности',
    'emergency.services.fireDesc': 'Пожары, утечки газа и спасательные операции',
    'emergency.importantNotice': 'Важное Уведомление',
    'emergency.onlyGenuineEmergencies': 'These are emergency contact numbers. Please only use them for genuine emergencies. For non-urgent matters, contact the appropriate non-emergency services.',
    'emergency.additionalInfo': 'Дополнительная Информация (Опционально)',
    'emergency.changeService': 'Изменить Службу',
    'emergency.addDetails': 'Добавить Детали',
    'emergency.additionalInfoPlaceholder': 'Предоставьте любую дополнительную информацию, которая может помочь службам экстренного реагирования...',
    'emergency.attachImage': 'Прикрепить Изображение (Опционально)',
    'emergency.uploadImage': 'Загрузить Изображение',
    'emergency.chooseImage': 'Выбрать Изображение',
    'emergency.dialerNote': 'You will be redirected to your phone\'s dialer app with the emergency number pre-filled. Please ensure you have a stable connection before proceeding.',
    'emergency.back': 'Назад',
    'emergency.call': 'Позвонить',

    // Navigation Modal
    'navigation.title': 'Навигация',
    'navigation.getDirections': 'Получите указания к вашей цели, используя карту ниже. Выберите место, чтобы начать навигацию.',
    'navigation.clickOnMap': 'Выберите Место',
    'navigation.mapUnavailable': 'Карта недоступна в этой демонстрации.',
    'navigation.findPlaces': 'Найдите места по имени или адресу',
    'navigation.nearbyLocations': 'Ближайшие Места',
    'navigation.trafficInfo': 'Информация о Трафике в Реальном Времени',
    'navigation.currentTraffic': 'Текущий Трафик',
    'navigation.savedRoutes': 'Сохранённые Маршруты',
    'navigation.frequentDestinations': 'Частые Места Назначения',

    //Penalty Management
    'penalties.myPenalties': 'Мои Штрафы',
    'penalties.activePenalties': 'Активные Штрафы',
    'penalties.totalPoints': 'Всего Очков',
    'penalties.unpaidFines': 'Неоплаченные Штрафы',
    'penalties.addPenalty': 'Добавить Штраф',


    // Service Management
    'service.title': 'Управление Услугами',
    'service.subtitle': 'Управляйте услугами автомобиля, записями технического обслуживания и важными датами.',
    'service.addService': 'Добавить Услугу',
    'service.type': 'Тип Услуги',
    'service.description': 'Описание',
    'service.price': 'Цена',
    'service.date': 'Дата Обслуживания',
    'service.expiryDate': 'Дата Истечения',
    'service.expires': 'Истекает',

    // Cards
    'cards.reportProblem.title': 'Сообщить о проблеме',
    'cards.reportProblem.description': 'Сообщайте о проблемах с транспортными средствами или дорожными условиями другим водителям',
    'cards.qrCode.title': 'Генерировать QR-код',
    'cards.qrCode.description': 'Создайте QR-код с информацией о вашем профиле и автомобиле',
    'cards.emergency.title': 'Экстренная помощь',
    'cards.emergency.description': 'Быстрый доступ к экстренным службам с дополнительными комментариями и изображениями',
    'cards.navigation.title': 'Навигация',
    'cards.navigation.description': 'Интерактивная навигация по карте, чтобы помочь вам найти дорогу',
    'cards.service.title': 'Сервис',
    'cards.service.description': 'Управляйте услугами для вашего автомобиля, страховкой и записями о техническом обслуживании',
    'cards.community.title': 'Сообщество',
    'cards.community.description': 'Общайтесь с другими водителями, добавляйте друзей и начинайте беседы',
    'cards.penalties.title': 'Управление штрафами',
    'cards.penalties.description': 'Просматривайте активные и неактивные дорожные штрафы, статус оплаты и управляйте водительской записью',
    'parkingCard': 'Умный помощник парковки',
    'parkingDescription': 'Найдите и проложите маршрут к доступным местам парковки',
    'emergencyCard': 'Службы экстренного реагирования',
    'emergencyDescription': 'Быстрый доступ к экстренным контактам и службам',
    'navigationCard': 'Умная навигация',
    'navigationDescription': 'Получите оптимизированные маршруты с обновлениями трафика в реальном времени',
    'communityCard': 'Функции сообщества',
    'communityDescription': 'Общайтесь с местными водителями и делитесь опытом',

    // Notifications
    'notifications.title': 'Уведомления о отчётах',
    'notifications.noReports': 'Отчёты ещё не получены',
    'notifications.newReport': 'Получен новый отчёт',
    'notifications.newReportDesc': 'Вы получили новый отчёт о вашем транспортном средстве.',
    'notifications.resolved': 'Решено',
    'notifications.pending': 'Ожидание',
    'notifications.vehicle': 'Транспорт',
    'notifications.reportDetails': 'Подробности отчёта',
    'notifications.noComment': 'Комментариев нет',
    'notifications.date': 'Дата',
    'notifications.evidencePhoto': 'Фото доказательство',
    'notifications.rateReport': 'Оценить этот отчёт (обязательно)',
    'notifications.yourResponse': 'Ваш ответ (необязательно)',
    'notifications.responsePlaceholder': 'Добавьте свой ответ на этот отчёт...',
    'notifications.close': 'Закрыть',
    'notifications.markResolved': 'Отметить как решённое',
    'notifications.resolving': 'Решается...',
    'notifications.reportResolved': 'Этот отчёт был решён',
    'notifications.ratingRequired': 'Требуется оценка',
    'notifications.ratingRequiredDesc': 'Пожалуйста, поставьте оценку, чтобы решить отчёт.',
    'notifications.resolveError': 'Не удалось решить отчёт. Попробуйте снова.',
    'notifications.reportResolvedTitle': 'Отчёт решён',
    'notifications.reportResolvedDesc': 'Спасибо за ваш ответ. Отчёт отмечен как решённый.',
    'notifications': 'Уведомления',
    'clearAll': 'Очистить все',
    'markAsRead': 'Отметить как прочитанное',
    'noNotifications': 'Нет уведомлений',
    'newNotification': 'Получено новое уведомление',
    'notificationMarkedRead': 'Уведомление отмечено как прочитанное',
    'allNotificationsCleared': 'Все уведомления очищены',
    'reportSubmitted': 'Отчет успешно отправлен',

    // Report types
    'wrongParking': 'Неправильная парковка',
    'weatherIssue': 'Проблема с погодой',
    'roadDamage': 'Повреждение дороги',
    'trafficLight': 'Светофор',
    'accident': 'Авария',
    'other': 'Другое',
    'notifications.details': 'Подробности',

    // Report modal
    'reportProblem': 'Сообщить о проблеме',
    'report.chooseMethod': 'Выберите метод отчёта',
    'report.scanQRCode': 'Сканировать QR-код',
    'report.scanQRCodeDesc': 'Используйте камеру, чтобы сканировать QR-код транспортного средства и сообщить о проблеме',
    'report.insertPlateNumber': 'Введите номерной знак',
    'report.insertPlateNumberDesc': 'Вручную введите номерной знак транспортного средства, чтобы сообщить о проблеме',
    'selectReportType': 'Выберите тип отчета',
    'report.whatProblem': 'Какую проблему вы хотите сообщить?',
    'description': 'Описание',
    'descriptionPlaceholder': 'Опишите проблему подробно...',
    'attachPhoto': 'Прикрепить фото',
    'cancel': 'Отмена',
    'submit': 'Отправить',

    // Profile Modal
    'profile': 'Профиль',
    'personal': 'Личные данные',
    'vehicles': 'Транспортные средства',
    'settings': 'Настройки',
    'personalInfo': 'Личная информация',
    'firstName': 'Имя',
    'lastName': 'Фамилия',
    'phone': 'Телефон',
    'firstNamePlaceholder': 'Введите ваше имя',
    'lastNamePlaceholder': 'Введите вашу фамилию',
    'phonePlaceholder': 'Введите номер телефона',
    'saveChanges': 'Сохранить изменения',
    'profileUpdated': 'Профиль успешно обновлен',
    'myVehicles': 'Мои транспортные средства',
    'addVehicle': 'Добавить транспортное средство',
    'noVehicles': 'Транспортные средства еще не добавлены',
    'addFirstVehicle': 'Добавьте ваше первое транспортное средство, чтобы начать',
    'brand': 'Марка',
    'model': 'Модель',
    'year': 'Год',
    'licensePlate': 'Номерной знак',
    'color': 'Цвет',
    'brandPlaceholder': 'например, Toyota',
    'modelPlaceholder': 'например, Camry',
    'yearPlaceholder': 'например, 2020',
    'licensePlatePlaceholder': 'например, ABC-123',
    'colorPlaceholder': 'например, Синий',
    'vehicleAdded': 'Транспортное средство успешно добавлено',
    'appSettings': 'Настройки приложения',
    'language': 'Язык',
    'theme': 'Тема',
    'pushNotifications': 'Push-уведомления',
    'emailNotifications': 'Email-уведомления',
    'smsNotifications': 'SMS-уведомления',
    'privacySecurity': 'Конфиденциальность и безопасность',
    'shareLocation': 'Делиться данными о местоположении',
    'shareUsageData': 'Делиться аналитикой использования',
    'logout': 'Выйти',
    'confirmLogout': 'Вы уверены, что хотите выйти?',

    // Admin
    'adminLogin': 'Вход администратора',
    'welcomeAdmin': 'Добро пожаловать, Администратор',
    'adminLoginDescription': 'Пожалуйста, введите ваши учетные данные администратора для доступа к панели управления',
    'emailPlaceholder': 'Введите email администратора',
    'passwordPlaceholder': 'Введите пароль администратора',
    'signInAsAdmin': 'Войти как администратор',
    'forgotPassword': 'Забыли пароль?',

    // Report Modal - Full translations
    'report.title': 'Сообщить о проблеме',
    'report.selectProblem': 'Выберите тип проблемы, о которой хотите сообщить:',
    'report.wrongParking': 'Неправильная парковка',
    'report.wrongParkingDesc': 'Транспортное средство припарковано в неразрешенном или неподходящем месте',
    'report.carProblem': 'Проблема с автомобилем',
    'report.carProblemDesc': 'Механические проблемы, поломка или неисправность транспортного средства',
    'report.forgottenLights': 'Забытые фары',
    'report.forgottenLightsDesc': 'Транспортное средство с оставленными включенными фарами, что может разрядить аккумулятор',
    'report.weatherIssue': 'Проблема с погодой',
    'report.weatherIssueDesc': 'Проблемы, связанные с погодой, влияющие на транспортные средства или движение',
    'report.suspiciousActivity': 'Подозрительная активность',
    'report.suspiciousActivityDesc': 'Необычное или вызывающее беспокойство поведение вокруг транспортных средств',
    'report.emergencyEvacuation': 'Экстренная эвакуация',
    'report.emergencyEvacuationDesc': 'Экстренная ситуация, требующая немедленной эвакуации',
    'report.vehiclePlateNumber': 'Номерной знак транспортного средства',
    'report.additionalDetails': 'Дополнительные детали (необязательно)',
    'report.photoEvidence': 'Фото доказательство (необязательно)',
    'report.takePhoto': 'Сделать фото',
    'report.uploadPhoto': 'Загрузить фото',
    'report.submitReport': 'Отправить отчёт',
    'report.back': 'Назад',
    'report.cancel': 'Отмена',
    'report.plateNumberPlaceholder': 'Введите номерной знак',
    'report.descriptionPlaceholder': 'Опишите, что произошло...',
    'report.registeredUser': 'Зарегистрированный пользователь',
    'report.unregisteredVehicle': 'Незарегистрированное транспортное средство',
    'report.photoHelp': 'Сделайте фото или загрузите доказательства для поддержки вашего отчёта',
    'report.submitting': 'Отправка...',

    // Landing Page - Hero Section
    'hero.badge': 'Полная платформа помощи водителям',
    'hero.title.part1': 'Все в одной',
    'hero.title.part2': 'Платформе для водителей',
    'hero.subtitle': 'Подключайтесь, сообщайте, навигируйте, общайтесь и управляйте всем, что связано с вождением, на одной мощной платформе. От QR-кодов до экстренных служб, от общения в сообществе до управления штрафами.',
    'hero.getStarted': 'Начать сейчас',
    'hero.exploreFeaturesBtn': 'Изучить функции',
    'hero.stats.drivers': 'Активные водители',
    'hero.stats.reports': 'Поданные отчёты',
    'hero.stats.emergency': 'Экстренные вызовы',
    'hero.stats.community': 'Участники сообщества',
    'hero.feature1': 'Поддержка в реальном времени',
    'hero.feature2': 'Интеграция QR-кода',
    'hero.feature3': 'Умная навигация',

    // Features Section
    'features.badge': 'Основные функции',
    'features.title.part1': 'Все что вам нужно',
    'features.title.part2': 'В одной платформе',
    'features.subtitle': 'От экстренной помощи до функций сообщества, наша платформа предоставляет комплексные инструменты для современных водителей.',
    'features.qr.title': 'Генерация QR-кода',
    'features.qr.description': 'Генерируйте уникальные QR-коды для профиля вашего автомобиля, которые могут сканировать другие водители или службы экстренного реагирования.',
    'features.reports.title': 'Сообщить о проблемах',
    'features.reports.description': 'Быстро сообщайте о нарушениях парковки, проблемах с автомобилем или других проблемах, чтобы информировать сообщество.',
    'features.emergency.title': 'Службы экстренного реагирования',
    'features.emergency.description': 'Прямой доступ к службам экстренного реагирования с обменом местоположением и документированием инцидентов.',
    'features.navigation.title': 'Умная навигация',
    'features.navigation.description': 'Интерактивные карты с обновлениями трафика в реальном времени и оптимизированной маршрутизацией для лучших поездок.',
    'features.security.title': 'Безопасность и конфиденциальность',
    'features.security.description': 'Ваши данные защищены корпоративной безопасностью и элементами управления конфиденциальностью, которым вы можете доверять.',
    'features.community.title': 'Сообщество водителей',
    'features.community.description': 'Общайтесь с другими водителями, делитесь опытом и создавайте поддерживающее сообщество водителей.',

    // Advanced Features Section
    'advanced.badge': 'Расширенные функции',
    'advanced.title.part1': 'Профессиональные инструменты',
    'advanced.title.part2': 'Для современных водителей',
    'advanced.subtitle': 'Расширенные инструменты управления и интеграции, предназначенные для профессиональных водителей и менеджеров автопарков.',
    'advanced.payment.title': 'Управление платежами',
    'advanced.payment.description': 'Безопасная обработка платежей за парковку, дорожные сборы и другие расходы, связанные с вождением.',
    'advanced.payment.stats': '99.9% Время работы',
    'advanced.penalty.title': 'Отслеживание штрафов',
    'advanced.penalty.description': 'Отслеживайте и управляйте нарушениями ПДД, штрафами и платежами за штрафы в одном месте.',
    'advanced.penalty.stats': 'В реальном времени',
    'advanced.vehicle.title': 'Управление транспортными средствами',
    'advanced.vehicle.description': 'Комплексные профили транспортных средств с отслеживанием технического обслуживания и документацией.',
    'advanced.vehicle.stats': 'Несколько ТС',
    'advanced.language.title': 'Многоязычная поддержка',
    'advanced.language.description': 'Платформа доступна на нескольких языках для глобальной доступности.',
    'advanced.language.stats': '3 языка',
    'advanced.interface.title': 'Темный/Светлый режим',
    'advanced.interface.description': 'Настраиваемые темы интерфейса для оптимального просмотра в любых условиях освещения.',
    'advanced.interface.stats': 'Адаптивный',
    'advanced.notifications.title': 'Умные уведомления',
    'advanced.notifications.description': 'Интеллектуальные оповещения и уведомления о важных обновлениях, связанных с вождением.',
    'advanced.notifications.stats': 'Push/Email',

    // Q&A Section
    'qa.badge': 'Часто задаваемые вопросы',
    'qa.title': 'Вопросы и ответы',
    'qa.subtitle': 'Найдите ответы на распространенные вопросы о нашей платформе и функциях.',
    'qa.question1': 'Как создать QR-код для моего автомобиля?',
    'qa.answer1': 'Просто перейдите в свою панель управления, нажмите на карточку QR-код, заполните информацию о вашем автомобиле и сгенерируйте уникальный QR-код. Затем вы можете распечатать его или сохранить в цифровом виде.',
    'qa.question2': 'Что делать в случае чрезвычайной ситуации?',
    'qa.answer2': 'Используйте функцию Службы экстренного реагирования в вашей панели управления. Выберите соответствующую службу (Полиция, Скорая помощь, Пожарная), добавьте любую релевантную информацию, и система поможет вам связаться со службами экстренного реагирования с указанием вашего местоположения.',
    'qa.question3': 'Как работает система отчетности?',
    'qa.answer3': 'Вы можете сообщать о различных проблемах, таких как неправильная парковка, проблемы с автомобилем или погодные проблемы. Просто выберите опцию Сообщить о проблеме, выберите тип проблемы, предоставьте подробности и при желании прикрепите фотографию.',
    'qa.question4': 'Безопасны ли мои личные данные?',
    'qa.answer4': 'Да, мы используем меры безопасности корпоративного уровня для защиты ваших данных. Вся информация зашифрована, и мы следуем строгим руководящим принципам конфиденциальности, чтобы обеспечить безопасность ваших данных.',
    'qa.question5': 'Могу ли я использовать платформу на нескольких языках?',
    'qa.answer5': 'Да, наша платформа поддерживает английский, румынский и русский языки. Вы можете изменить язык в настройках или используя переключатель языка в навигации.',
    'qa.question6': 'Как общаться с другими водителями?',
    'qa.answer6': 'Используйте функции Сообщества для поиска других водителей, отправки запросов на дружбу и начала разговоров. Вы можете найти водителей по имени или деталям автомобиля и построить сеть коллег-водителей.',

    // Footer
    'footer.brand': 'DAP',
    'footer.subtitle': 'Платформа помощи водителям',
    'footer.description': 'Соединяем водителей по всему миру с инновационными функциями безопасности, службами экстренного реагирования и системами отчетности, управляемыми сообществом.',
    'footer.contact': 'Свяжитесь с нами',
    'footer.copyright': '© 2025 DAP - Платформа помощи водителям. Все права защищены.',
    'footer.tagline': 'Создано с учетом безопасности и инноваций.',

    // Mobile Navigation
    'mobile.myProfile': 'Мой Профиль',
    'mobile.quickReport': 'Быстрый Отчёт',

    // Common
    'language.english': 'English',
    'language.romanian': 'Română',
    'language.russian': 'Русский',
  }
};

export function LanguageProvider({
  children,
  defaultLanguage = 'en',
  storageKey = 'lovable-language',
  ...props
}: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(() => {
    try {
      const stored = localStorage.getItem(storageKey);
      return (stored as Language) || defaultLanguage;
    } catch {
      return defaultLanguage;
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem(storageKey, language);
    } catch {
      // Ignore localStorage errors
    }
  }, [language, storageKey]);

  const t = (key: string): string => {
    try {
      const translation = translations[language]?.[key] || key;
      return typeof translation === 'string' ? translation : key;
    } catch {
      return key;
    }
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageProviderContext.Provider {...props} value={value}>
      {children}
    </LanguageProviderContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageProviderContext);

  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }

  return context;
};