// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqkeudswplvxxmunoggh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxa2V1ZHN3cGx2eHhtdW5vZ2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODkzOTYsImV4cCI6MjA2ODg2NTM5Nn0.bLnBRmW-nE0bra3Qqom4HHYUz-WyNDNPq1VFXJVOIEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});